# docker-cloud.yml
version: "3.7"
services:
  mongo-app:
    image: twcammaster.uv.es/proyecto-8-mongo-app  
    ports:
      - target: 8083
        published: 8083
    depends_on:
      - mongo-server-docker
    networks:
      - internal
  mongo-server-docker:
    image: mongo:3.4.2    
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - internal
  mysql-app:
    image: twcammaster.uv.es/proyecto-8-mysql-app  
    ports:
      - target: 8082
        published: 8082
    depends_on:
      - mysql-container
    networks:
      - internal
  mysql-container:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=airlinesdb
    ports:
      - "3306:3306"
    networks:
      - internal
networks:
  internal: